name: arm build

on: 
  workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm64" ]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 8
        
    - name: Set up GCC
      run: |
        sudo apt-get -y install gcc-aarch64-linux-gnu
        sudo apt-get -y install g++-aarch64-linux-gnu
      
    - name: Build for ${{matrix.arch}}
      run: |
        export JAVA8_HOME=$JAVA_HOME_8_${{runner.arch}}
        export LWJGL_BUILD_ARCH=${{matrix.arch}}
        bash ci_build.bash

    - name: Upload modules release output
      if: ${{matrix.arch == 'arm64'}} # Only upload this once
      uses: actions/upload-artifact@v6
      with:
        name: lwjgl3-modules
        path: bin/RELEASE

    - name: Upload native build output
      uses: actions/upload-artifact@v6
      with:
        name: lwjgl3-natives-${{matrix.arch}}
        path: bin/out
