name: arm build

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: set up JDK 8
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 8

    - name: set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17
        
    - name: Set up GCC
      run: |
        sudo apt-get -y update
        sudo apt-get -y install gcc-aarch64-linux-gnu
        sudo apt-get -y install g++-aarch64-linux-gnu
        sudo apt-get -y install build-essential
      
    - name: Build for arm64
      run: |
        export JAVA8_HOME=$JAVA_HOME_8_${{runner.arch}}
        bash ci_build.bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.ref_name }}
        path: bin/RELEASE/lwjgl-openvr
        retention-days: 1
        if-no-files-found: error
    - name: github release
      uses: softprops/action-gh-release@v3
      with:
        files: bin/RELEASE/lwjgl-openvr/lwjgl-openvr-natives-linux-arm64.jar
        target_commitish: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
